In [17]:
import yaml

In [1]:
from dataclasses import dataclass
@dataclass()
class User:
    name:str=None
    address:[]=None

In [18]:
from yaml import dump,load

In [25]:
user=User()
getattr(type(user),name)

NameError: name 'name' is not defined

In [13]:
d=load("{'name':'test'}")

/Users/modongsong/.pyenv/versions/anaconda3-5.3.0/envs/pytorch/lib/python3.6/site-packages/ipykernel_launcher.py:1: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """Entry point for launching an IPython kernel.


In [14]:
type()

NameError: name 'd' is not defined

In [16]:
User().__dict__

{'name': ''}

In [17]:
type(User().__dict__)

dict

In [22]:
for item in User().__dict__.items():
    print(item)

('name', '')


In [23]:
type(User())

__main__.User

In [29]:
a=type(User()).__dict__

In [37]:
type(a.get('__dataclass_fields__'))

dict

In [8]:
def get(user,name):
    return getattr(user,name)

In [13]:
get(User(),'name')

In [29]:
class Test:
    def add(self,v):
        print(v)
        return self

In [30]:
(Test()
 .add(1)
 .add(1)
 .add(2)
 .add(3)
)

1
1
2
3


In [31]:
type(User)

type

In [32]:
type(User)==type

True

In [36]:
a={"name":"name"}
a.get("name1")

In [39]:
User.a='name'

In [40]:
a=User()
user.a="test"

In [41]:
user.a

'test'

In [42]:
user.b="help"

In [43]:
user.b

'help'

In [44]:
setattr(user,'c','test')

In [45]:
user.c

'test'

In [46]:
getattr(user,'bb')

AttributeError: 'User' object has no attribute 'bb'

In [49]:
user.a

'test'

In [50]:
dict().get('name')

In [51]:
a=10e6

In [52]:
print(a)

10000000.0


In [59]:
a=256e6

In [61]:
list=[1,2,3,4]

In [62]:
list.size()

AttributeError: 'list' object has no attribute 'size'

In [63]:
import torch

In [64]:
a=torch.Tensor([1,2,3,4,5,6,7])

In [65]:
a

tensor([1., 2., 3., 4., 5., 6., 7.])

In [67]:
torch.topk(a,3)[0]

tensor([7., 6., 5.])

In [94]:
a<torch.topk(a,3)[0][...,-1,None]

tensor([ True,  True,  True,  True, False, False, False])

In [95]:
import torch.nn.functional as F

In [105]:
a0,a1=torch.sort(a, descending=True)
b=torch.cumsum(F.softmax(a0,dim=-1),dim=-1)

In [106]:
a0,a1,b

(tensor([7., 6., 5., 4., 3., 2., 1.]),
 tensor([6, 5, 4, 3, 2, 1, 0]),
 tensor([0.6327, 0.8655, 0.9511, 0.9826, 0.9942, 0.9984, 1.0000]))

In [111]:
F.softmax(a0,dim=-1)

tensor([0.6327, 0.2328, 0.0856, 0.0315, 0.0116, 0.0043, 0.0016])

In [103]:
b>0.5

tensor([False, False, False, False, False, False,  True])

In [108]:
c=b>0.9

In [109]:
c[...,0]

tensor(False)

In [110]:
a1[c]

tensor([4, 3, 2, 1, 0])

In [113]:
d=torch.multinomial(F.softmax(a, dim=-1), num_samples=1)

In [114]:
d.item()

6

In [126]:
torch.arange(len(torch.ones(3,10)))

tensor([0, 1, 2])

In [127]:
torch.Tensor.unsqueeze??

Docstring:
unsqueeze(dim) -> Tensor

See :func:`torch.unsqueeze`
Type:      method_descriptor


In [128]:
torch.unsqueeze??

Docstring:
unsqueeze(input, dim, out=None) -> Tensor

Returns a new tensor with a dimension of size one inserted at the
specified position.

The returned tensor shares the same underlying data with this tensor.

A :attr:`dim` value within the range ``[-input.dim() - 1, input.dim() + 1)``
can be used. Negative :attr:`dim` will correspond to :meth:`unsqueeze`
applied at :attr:`dim` = ``dim + input.dim() + 1``.

Args:
    input (Tensor): the input tensor.
    dim (int): the index at which to insert the singleton dimension
    out (Tensor, optional): the output tensor.

Example::

    >>> x = torch.tensor([1, 2, 3, 4])
    >>> torch.unsqueeze(x, 0)
    tensor([[ 1,  2,  3,  4]])
    >>> torch.unsqueeze(x, 1)
    tensor([[ 1],
            [ 2],
            [ 3],
            [ 4]])
Type:      builtin_function_or_method


In [129]:
x=torch.tensor([1,2,3,4])

In [132]:
torch.unsqueeze(x,-2)

tensor([[1, 2, 3, 4]])

In [133]:
a={'name':1}

In [134]:
a.update??

Docstring:
D.update([E, ]**F) -> None.  Update D from dict/iterable E and F.
If E is present and has a .keys() method, then does:  for k in E: D[k] = E[k]
If E is present and lacks a .keys() method, then does:  for k, v in E: D[k] = v
In either case, this is followed by: for k in F:  D[k] = F[k]
Type:      builtin_function_or_method


In [135]:
b={'name':2,'age':1}

In [136]:
a.update(b)

In [137]:
a

{'age': 1, 'name': 2}